export const SEARCH_APPLICANTS = 'SEARCH_APPLICANTS';
export const SUCCESS_APPLICANTS = 'SUCCESS_APPLICANTS';
export const ERROR_APPLICANTS = 'ERROR_APPLICANTS';
export const SEARCH_APPLICANT = 'SEARCH_APPLICANT';
export const SUCCESS_APPLICANT = 'SUCCESS_APPLICANT';
export const ERROR_APPLICANT = 'ERROR_APPLCIANT';
