export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';
export const SUBMIT_APPLICATION_SUCCESS = 'SUBMIT_APPLICATION_SUCCESS';
export const SUBMIT_APPLICATION_FAILED = 'SUBMIT_APPLICATION_FAILED';
export const DISCARD_APPLICATION = 'DISCARD_APPLICATION';
export const SUBMIT_EXPERTISE = 'SUBMIT_EXPERTISE';
export const SUBMIT_AVAILABILITY_PERIOD = 'SUBMIT_AVAILABILITY_PERIOD';
