//Import Controllers
const repositoryController = require('./users.repository');

/**
 * @public
 * @description Creates a user profile in the database
 * with given information in the data object.
 * @param {object} data User data
 *    Example: {
 *      uid (str),
 *      name (str),
 *      surname (str),
 *      ssn (str),
 *    }
 * @returns {str} 
 */
exports.createUserProfile = async (data) => (
  await repositoryController.createUserProfile(data)
);

/**
 * @public
 * @description Gets user data 
 * @param {str} uid User ID auto generated by firebase 
 * when creating an account.
 * @returns {str} Message  
 */
exports.getUserProfile = async (uid) => (
  await repositoryController.getUserProfile(uid)
)
