export const API_URL = 'DISCARD_APPLICATION';
export const AREA_OF_EXPERTISE_SUBMIT = 'SUBMIT_EXPERTISE';
export const AREA_OF_EXPERTISE_FETCH = 'FETCH_EXPERTISE';
export const AREA_OF_EXPERTISE_RECEIVED= 'RECEIVED_EXPERTISE'
export const YEARS_OF_EXPERIENCE_SUBMIT = 'SUBMIT_EXPERIENCE';
