export const AREA_OF_EXPERTISE_FETCH_FAILED = 'AREA_OF_EXPERTISE_FETCH_FAILED';
export const AREA_OF_EXPERTISE_SUBMIT = 'SUBMIT_EXPERTISE';
export const AREA_OF_EXPERTISE_FETCH = 'FETCH_EXPERTISE';
export const AREA_OF_EXPERTISE_RECEIVED = 'RECEIVED_EXPERTISE';
export const AVAILABILITY_PERIOD_SUBMIT = 'SUBMIT_AVAILABILITY_PERIOD';
